### ISSUE TITLE
New layer list UI

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/GlobalFishingWatch#723]

**Comment by Bluesmile82** [comment]
This might be more than 3 points. We will have to:

- Add delete layer
- Use new color picker
- Show polygons with colors
- Select a polygon and display info in a tooltip

**Comment by tiagojsag** [comment]
- Delete layer: already done, just needs a restyle on the button
- New color picker: yes, this is new, but it's also reused on different parts of the page,
- Polygons wit colors: that's an extra, let's not do it for now
- Select a polygon and display info: https://github.com/Vizzuality/GlobalFishingWatch/issues/682
