### ISSUE TITLE
Include flags filters in AIS tileset headers

### ISSUE THREAD

**Issue by nerik** [Vizzuality/GlobalFishingWatch#803]
There are cases were a filter is supported on a layer but selection ends up being empty. 

The only case I see for now is the AIS layer when applying some flags. We already removed landlocked countries on our side, but maybe at this point it would be useful to have the available flags in the AIS tileset headers.

**Comment by enriquetuya** [comment]
@nerik this is correct. There may be values in the filters that have no options. One case is INDONESIA that all data is present in VMS but not in AIS. We include all countries on the header and not take into account if there is data available. We could change this, but is not a top priority.
