### ISSUE TITLE
Clarify filter group modal

### ISSUE THREAD

**Issue by nerik** [Vizzuality/GlobalFishingWatch#804]
The feature works well, but it is not very intuitive for an unfamiliar user. I think we should add some guidance text to the user or some `?` help. Specially I had a hard time understanding (if I understood correctly) how the checkboxes and the filters work.  Also we should add some disclaimer that not all data has labels, and that not seeing data after filtering means that no fishing events have occurred. 

Here's a quick proposal that consists of adding explanatory text and fix section headers wording:
![screen shot 2017-10-20 at 09 18 10](https://user-images.githubusercontent.com/1583415/31809649-f2d2c35a-b578-11e7-9836-3f0b56bc54db.png)

We could add a contextual warning that is triggered when applying an unsupported filter on a layer:
![screen shot 2017-10-20 at 09 26 52](https://user-images.githubusercontent.com/1583415/31809696-0fe65aa6-b579-11e7-9817-cce0992a1b96.png)

There are other cases were filter is supported but selection ends up being empty. See: https://github.com/Vizzuality/GlobalFishingWatch/issues/803

**Comment by enriquetuya** [comment]
@nerik I like the approach for a first version.
