### ISSUE TITLE
Filter Groups : API should indicate available flags 

### ISSUE THREAD

**Issue by nerik** [Vizzuality/GlobalFishingWatch#813]
The length of the flags list makes it hard to navigate, plus a lot of countries don't yield results, which can be frustrating to the user.

- [ ] API changes
- [ ] remove hardcoded behavior on the frontend

**Comment by enriquetuya** [comment]
@nerik in case we have different amount of countries on the multiple tiles. The values will get merged? For instance:
tile 1 only have peru
tile 2 only have indonesia

The combo will display peru and indonesia?

**Comment by nerik** [comment]
No, currently, the logic will just take the first item of all filters that have the same `id`.
We could implement this relatively easily though (concatenate all filters values and remove duplicates by value, provided there are never 2 different labels for the same value)

**Comment by nerik** [comment]
Not needed anymore with type in filters.
