### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by nerik** [Vizzuality/GlobalFishingWatch#815]
(From @enriquetuya)
I was just checking the 2.2.1-RC3 on our test environment. This version is the one that contains the new Vizz logo. After trying it out, the one that @ariadna sent back then seems much better than the current one: https://globalfishingwatch.slack.com/files/U6VDT463F/F7P098FCL/02__new_.jpg

Let's move ahead and use that one instead. we already have Paul's approval.

The problems I find with RC3 are:
- Both header and sub-header are not that sharp neither on mobile or desktop.
- Global Fishing Watch is much smaller than the current production logo.
- The vertical allignment of the logo and the text is much better on Ariadna's version

Both issues are fine on the mock that @ariadna sent. 

![02 _new](https://user-images.githubusercontent.com/1583415/32229874-1d771106-be52-11e7-8197-bc2275de09e1.jpg)

**Comment by enriquetuya** [comment]
some of the logo issues that can be find in `2.2.1-RC3` can be seen below
![logo1](https://user-images.githubusercontent.com/355597/32231062-6043b814-be33-11e7-9dab-65612ee9f683.png)
![logo2](https://user-images.githubusercontent.com/355597/32231064-607ff0a4-be33-11e7-8041-0c2120da4635.png)

**Comment by nerik** [comment]
Only talking about the logo, not header layout: do you confirm that the logo we should use is the one altered by Ariadna, as seen in the following screenshot? :

![preview3](https://user-images.githubusercontent.com/1583415/32237351-032ebdcc-be65-11e7-9d57-b6722d1ff2ce.png)

**Comment by nerik** [comment]
Note that this is *not* the last version that you sent us, which looks like this:

![screen shot 2017-10-31 at 18 05 42](https://user-images.githubusercontent.com/1583415/32237763-22a767a2-be66-11e7-8ce5-7cd75fccc8eb.png)

(bigger fishes compared to text, text is closer to fishes)

**Comment by enriquetuya** [comment]
I confirm the one is this one: 
![preview3](https://user-images.githubusercontent.com/1583415/32237351-032ebdcc-be65-11e7-9d57-b6722d1ff2ce.png)
shown here: https://github.com/Vizzuality/GlobalFishingWatch/issues/815#issuecomment-340829497

**Comment by nerik** [comment]
Ok, thanks
